/**
 * Türkçe UI Metinleri - Merkezi Kaynak
 * Tüm UI metinleri bu dosyadan yönetilir
 */

export const TR = {
  // Common / Genel
  common: {
    loading: "Yükleniyor...",
    save: "Kaydet",
    cancel: "İptal",
    delete: "Sil",
    edit: "Düzenle",
    create: "Oluştur",
    close: "Kapat",
    search: "Ara...",
    filter: "Filtrele",
    all: "Tümü",
    active: "Aktif",
    inactive: "Pasif",
    yes: "Evet",
    no: "Hayır",
    actions: "İşlemler",
    details: "Detaylar",
    back: "Geri",
    next: "İleri",
    previous: "Önceki",
    submit: "Gönder",
    confirm: "Onayla",
    view: "Görüntüle",
    download: "İndir",
    upload: "Yükle",
    refresh: "Yenile",
    select: "Seç",
    clear: "Temizle",
    apply: "Uygula",
    reset: "Sıfırla",
    export: "Dışa Aktar",
    import: "İçe Aktar",
  },

  // Admin Dashboard
  admin: {
    title: "Ana Panel",
    subtitle: "Organizasyon ve Kullanıcı Yönetim Sistemi",
    totalSites: "Toplam Site",
    departments: "Departmanlar",
    totalUsers: "Toplam Kullanıcı",
    ratingCriteria: "Değerlendirme Kriterleri",
    quickActions: "Hızlı İşlemler",
    createSite: "Site Oluştur",
    createSiteDesc: "Sisteme yeni bir site ekle",
    createDepartment: "Departman Oluştur",
    createDepartmentDesc: "Bir site'ye yeni departman ekle",
    addUser: "Kullanıcı Ekle",
    addUserDesc: "Yeni kullanıcı hesabı oluştur",
    defineCriteria: "Kriter Tanımla",
    defineCriteriaDesc: "Departmanlar için değerlendirme kriterleri belirle",
    yourAccessLevel: "Erişim Seviyeniz",
    fullSystemAccess: "Tam sistem erişimi",
    manageAllSites: "Tüm site ve departmanları yönet",
    manageAllUsers: "Tüm kullanıcıları oluştur ve yönet",
    configureCriteria: "Değerlendirme kriterlerini yapılandır",
    accessYourSite: "Sadece kendi site'nize erişim",
    manageYourSiteUsers: "Site'nizdeki kullanıcıları yönet",
    assignRoles: "Rol ata (MANAGER, STAFF)",
    cannotCreateSites: "Site ve departman oluşturamazsınız",
  },

  // Users
  users: {
    title: "Kullanıcı Yönetimi",
    createNew: "Yeni Kullanıcı",
    searchPlaceholder: "Ad, email veya departman ara...",
    filterByRole: "Role göre filtrele",
    filterByStatus: "Duruma göre filtrele",
    filterByDepartment: "Departmana göre filtrele",
    name: "Ad",
    email: "Email",
    role: "Rol",
    department: "Departman",
    status: "Durum",
    createdAt: "Oluşturulma",
    noUsers: "Kullanıcı Bulunamadı",
    noUsersDesc: "Henüz hiç kullanıcı oluşturulmamış",
    noMatch: "Eşleşen kullanıcı bulunamadı",
    noMatchDesc: "Farklı filtreler deneyin",
    editUser: "Kullanıcıyı Düzenle",
    createUser: "Kullanıcı Oluştur",
    userInfo: "Kullanıcı Bilgileri",
    selectSite: "Site seçin",
    selectDepartment: "Departman seçin (opsiyonel)",
    selectRole: "Rol seçin",
    tempPassword: "Geçici Şifre",
    tempPasswordCopied: "Geçici şifre kopyalandı!",
    tempPasswordNote: "Bu şifre yalnızca bir kez gösterilir. Kullanıcı ilk girişte şifre değiştirmek zorunda kalacak.",
    copyPassword: "Şifreyi Kopyala",
    userCreatedSuccess: "Kullanıcı başarıyla oluşturuldu",
    userUpdatedSuccess: "Kullanıcı başarıyla güncellendi",
    userDeletedSuccess: "Kullanıcı başarıyla silindi",
    deleteConfirm: "Bu kullanıcıyı silmek istediğinizden emin misiniz?",
    deleteWarning: "Bu işlem geri alınamaz.",
  },

  // Sites
  sites: {
    title: "Site Yönetimi",
    createNew: "Yeni Site",
    siteName: "Site Adı",
    usersCount: "Kullanıcı",
    departmentsCount: "Departman",
    createdAt: "Oluşturulma",
    noSites: "Site Bulunamadı",
    noSitesDesc: "Henüz hiç site oluşturulmamış. Başlamak için bir site oluşturun.",
    createSite: "Site Oluştur",
    editSite: "Site'yi Düzenle",
    siteCreatedSuccess: "Site başarıyla oluşturuldu",
    siteUpdatedSuccess: "Site başarıyla güncellendi",
    siteDeletedSuccess: "Site başarıyla silindi",
    deleteConfirm: "Bu site'yi silmek istediğinizden emin misiniz?",
    deleteWarning: "Site ile ilişkili tüm departmanlar ve kullanıcılar da silinecektir. Bu işlem geri alınamaz.",
  },

  // Departments
  departments: {
    title: "Departman Yönetimi",
    createNew: "Yeni Departman",
    departmentName: "Departman Adı",
    site: "Site",
    usersCount: "Kullanıcı",
    criteriaCount: "Kriter",
    createdAt: "Oluşturulma",
    noDepartments: "Departman Bulunamadı",
    noDepartmentsDesc: "Henüz hiç departman oluşturulmamış.",
    createDepartment: "Departman Oluştur",
    editDepartment: "Departmanı Düzenle",
    selectSite: "Site seçin",
    departmentCreatedSuccess: "Departman başarıyla oluşturuldu",
    departmentUpdatedSuccess: "Departman başarıyla güncellendi",
    departmentDeletedSuccess: "Departman başarıyla silindi",
    deleteConfirm: "Bu departmanı silmek istediğinizden emin misiniz?",
    deleteWarning: "Departman ile ilişkili tüm kullanıcılar ve kriterler de silinecektir.",
  },

  // Rating Criteria
  criteria: {
    title: "Değerlendirme Kriterleri",
    createNew: "Yeni Kriter",
    criteriaName: "Kriter Adı",
    weight: "Ağırlık",
    status: "Durum",
    department: "Departman",
    noCriteria: "Kriter Bulunamadı",
    noCriteriaDesc: "Henüz hiç değerlendirme kriteri tanımlanmamış.",
    createCriteria: "Kriter Oluştur",
    editCriteria: "Kriteri Düzenle",
    totalWeight: "Toplam Ağırlık",
    selectDepartment: "Departman seçin",
    criteriaCreatedSuccess: "Kriter başarıyla oluşturuldu",
    criteriaUpdatedSuccess: "Kriter başarıyla güncellendi",
    criteriaDeletedSuccess: "Kriter başarıyla silindi",
    weightDistribution: "Ağırlık Dağılımı",
  },

  // Sessions
  sessions: {
    title: "Oturum Yönetimi",
    currentSession: "Mevcut Oturumunuz",
    otherSessions: "Diğer Oturumlar",
    device: "Cihaz",
    ipAddress: "IP Adresi",
    lastSeen: "Son Görülme",
    createdAt: "Oluşturulma",
    revoke: "İptal Et",
    revokeAll: "Tümünü İptal Et",
    noSessions: "Başka Oturum Yok",
    noSessionsDesc: "Başka aktif oturumunuz bulunmuyor.",
    revokeConfirm: "Bu oturumu iptal etmek istediğinizden emin misiniz?",
    revokeAllConfirm: "Tüm diğer oturumları iptal etmek istediğinizden emin misiniz?",
    sessionRevokedSuccess: "Oturum iptal edildi",
    sessionsRevokedSuccess: "Oturumlar iptal edildi",
  },

  // Security Events
  security: {
    title: "Güvenlik Olayları",
    subtitle: "Sistemdeki güvenlik olaylarını izleyin ve yönetin",
    eventType: "Olay Türü",
    site: "Site",
    user: "Kullanıcı",
    timestamp: "Zaman",
    status: "Durum",
    resolved: "Çözüldü",
    unresolved: "Çözülmedi",
    resolve: "Çözümle",
    unresolve: "Çözümü Geri Al",
    bulkResolve: "Toplu Çözümle",
    selectAll: "Tümünü Seç",
    selected: "seçildi",
    filterByType: "Türe göre filtrele",
    filterByStatus: "Duruma göre filtrele",
    filterByTimeRange: "Zamana göre filtrele",
    filterBySite: "Site'ye göre filtrele",
    last24h: "Son 24 saat",
    last7d: "Son 7 gün",
    last30d: "Son 30 gün",
    last90d: "Son 90 gün",
    noEvents: "Güvenlik Olayı Bulunamadı",
    noEventsDesc: "Sistemde henüz güvenlik olayı kaydedilmemiş.",
    noMatch: "Eşleşen olay bulunamadı",
    noMatchDesc: "Farklı filtreler deneyin",
    eventDetails: "Olay Detayları",
    eventInformation: "Olay Bilgileri",
    contextInformation: "Bağlam Bilgileri",
    metadata: "Meta Veriler",
    resolvedSuccess: "Güvenlik olayı çözümlendi",
    unresolvedSuccess: "Çözüm geri alındı",
    bulkResolvedSuccess: "seçili olay çözümlendi",
  },

  // Arena
  arena: {
    title: "Arena",
    subtitle: "Canlı Performans ve Yarışma Platformu",
    rankings: "Sıralamalar",
    rankingsDesc: "Gerçek zamanlı lider tabloları",
    liveEvents: "Canlı Olaylar",
    liveEventsDesc: "Aktivite akışı güncellemeleri",
    analytics: "Analitik",
    analyticsDesc: "Performans içgörüleri",
    phase1: "Faz 1: Canlı Akış",
    phase1Desc: "Bu, Arena implementasyonunun ilk fazıdır. Şu anda gerçek zamanlı olay akışı gösteriliyor. Puanlama algoritmaları, lig hesaplamaları ve AI içgörüleri gibi gelişmiş özellikler gelecek fazlarda eklenecektir.",
    liveFeed: "Arena Canlı Akış",
    liveFeedDesc: "Gerçek zamanlı aktivite akışı",
    live: "Canlı",
    comingSoon: "Yakında",
    leagueSystem: "Lig Sistemi",
    leagueSystemDesc: "Bronz, Gümüş, Altın, Platin seviyeleri",
    scoreEngine: "Puan Motoru",
    scoreEngineDesc: "Gelişmiş değerlendirme hesaplamaları",
    performanceCharts: "Performans Grafikleri",
    performanceChartsDesc: "Görsel analitik ve trendler",
    aiInsights: "AI İçgörüleri",
    aiInsightsDesc: "Akıllı öneriler",
    yourAccess: "Erişiminiz",
    viewingAllSites: "Tüm Site'ler",
    viewingYourSite: "Sadece Kendi Site'niz",
    events: "olay",
    noRecentActivity: "Yakın Zamanda Aktivite Yok",
    noActivityDesc: "Arena olayları gerçekleştikçe burada görünecek",
    showingLast: "Son",
    eventsShown: "olay gösteriliyor",
    newestFirst: "Yeniden eskiye",
    justNow: "Şimdi",
    minutesAgo: "dk önce",
    hoursAgo: "sa önce",
    daysAgo: "gün önce",
    event: "olay",
    total: "toplam",
  },

  // Errors
  errors: {
    accessDenied: "Erişim Reddedildi",
    accessDeniedDesc: "Bu sayfaya erişim yetkiniz yok.",
    userManagementDenied: "Kullanıcı yönetimine erişim yetkiniz yok.",
    errorLoading: "Yükleme Hatası",
    errorLoadingArena: "Arena Yüklenirken Hata",
    somethingWentWrong: "Bir şeyler yanlış gitti",
    tryAgain: "Tekrar deneyin",
    notFound: "Bulunamadı",
    pageNotFound: "Sayfa bulunamadı",
    userNotFound: "Kullanıcı bulunamadı",
    siteNotFound: "Site bulunamadı",
    departmentNotFound: "Departman bulunamadı",
    eventNotFound: "Olay bulunamadı",
    invalidInput: "Geçersiz giriş",
    requiredField: "Bu alan zorunludur",
    invalidEmail: "Geçersiz email adresi",
    unauthorized: "Yetkisiz",
    forbidden: "Yasak",
    serverError: "Sunucu hatası",
    networkError: "Ağ hatası",
  },

  // Success Messages
  success: {
    saved: "Başarıyla kaydedildi",
    updated: "Başarıyla güncellendi",
    deleted: "Başarıyla silindi",
    created: "Başarıyla oluşturuldu",
    copied: "Kopyalandı",
    sent: "Gönderildi",
    completed: "Tamamlandı",
  },

  // Roles
  roles: {
    SUPER_ADMIN: "Süper Yönetici",
    ADMIN: "Yönetici",
    MANAGER: "Müdür",
    STAFF: "Personel",
  },

  // Status
  status: {
    active: "Aktif",
    inactive: "Pasif",
    pending: "Beklemede",
    completed: "Tamamlandı",
    failed: "Başarısız",
    success: "Başarılı",
    error: "Hata",
    warning: "Uyarı",
    info: "Bilgi",
  },

  // Time
  time: {
    today: "Bugün",
    yesterday: "Dün",
    thisWeek: "Bu Hafta",
    thisMonth: "Bu Ay",
    lastWeek: "Geçen Hafta",
    lastMonth: "Geçen Ay",
    last24h: "Son 24 Saat",
    last7d: "Son 7 Gün",
    last30d: "Son 30 Gün",
    last90d: "Son 90 Gün",
    custom: "Özel",
  },

  // Pagination
  pagination: {
    showing: "Gösteriliyor",
    of: "/",
    results: "sonuç",
    page: "Sayfa",
    perPage: "Sayfa başına",
    first: "İlk",
    last: "Son",
    previous: "Önceki",
    next: "İleri",
  },
} as const

// Type helper for autocomplete
export type TRKeys = typeof TR
